//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveMarket.Core.Repositories.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlyingCircusEntities : DbContext
    {
        public FlyingCircusEntities()
            : base("name=FlyingCircusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ImportItem> ImportItems { get; set; }
        public virtual DbSet<MineralQuote> MineralQuotes { get; set; }
        public virtual DbSet<MarketOrder> MarketOrders { get; set; }
    }
}
