//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveMarket.Core.Repositories.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MineralQuote
    {
        public System.Guid Id { get; set; }
        public string QuoteLookup { get; set; }
        public string PlayerName { get; set; }
        public Nullable<int> TritaniumQty { get; set; }
        public Nullable<int> PyeriteQty { get; set; }
        public Nullable<int> MexallonQty { get; set; }
        public Nullable<int> IsogenQty { get; set; }
        public Nullable<int> NocxiumQty { get; set; }
        public Nullable<int> ZydrineQty { get; set; }
        public Nullable<int> MegacyteQty { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Shipping { get; set; }
        public Nullable<decimal> Total { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public Nullable<int> MorphiteQty { get; set; }
    }
}
